apiVersion: v1
kind: Service
metadata:
  name: webrtc-signaling-service
spec:
  type: NodePort
  selector:
    app: webrtc-signaling
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30003