apiVersion: v1
kind: Service
metadata:
  name: rov-streamer-service
spec:
  type: NodePort           # 1. Change type to NodePort
  selector:
    app: webrtc-streamer-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001      # 2. Expose on Host Port 30001
---
apiVersion: v1
kind: Service
metadata:
  name: rov-cam-streamer-service 
spec:
  type: NodePort           # 1. Change type to NodePort
  selector:
    app: webrtc-streamer-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002      # 2. Expose on Host Port 30002