main_ros_image: "mantaray.local:5000/manta-ray-ros:latest"
microros_image: "mantaray.local:5000/microros-with-esptool:0.1"
web_ui_image: "mantaray.local:5000/mantaray-control-interface:latest"

all_app_deployments:
  - controller-deployment
  # - ui-node-deployment
  - receiver-deployment
  # - http-image-getter-a-deployment
  # - http-image-getter-b-deployment
  # - capture-image-deployment
  # - save-image-deployment
  # - morse-code-deployment
  - foxglove-bridge-deployment
  - msg-converter-deployment
  - webrtc-streamer-a-deployment
  - webrtc-streamer-b-deployment
  - thrusterboard-deployment
  - pid-system-deployment
  - microros-agent-deployment
  - rosbridge-server-deployment
  - webui-deployment