[all:vars]
# This sets the default user for all hosts in this file
ansible_user=edwin
force_k3s_reinstall=false
# Change this to 'wlan' to revert everyone to Wi-Fi
connection_mode=eth

[k3s_server]
# This host will use the default 'ansible_user=edwin'
# IP change detection: Update the IP when it changes. This will trigger a full cluster reinstall.
mantaray.local ansible_k3s_server_ip=192.168.3.124 ansible_host=192.168.3.124

[k3s_agents]
# These hosts override the default user
rov.local     ansible_user=EEC ansible_k3s_agent_ip=192.168.3.211 ansible_host=192.168.3.211
rov-cam.local ansible_user=EEC ansible_k3s_agent_ip=192.168.3.246 ansible_host=192.168.3.246

[k3s_agents:vars]
ansible_python_interpreter=/usr/bin/python3

[all_nodes:children]
k3s_server
k3s_agents