[all:vars]
# This sets the default user for all hosts in this file
ansible_user=edwin

[k3s_server]
# This host will use the default 'ansible_user=edwin'
mantaray.local

[k3s_agents]
# These hosts override the default user
rov.local     ansible_user=EEC
rov-cam.local ansible_user=EEC

[k3s_agents:vars]
ansible_python_interpreter=/usr/bin/python3

[all_nodes:children]
k3s_server
k3s_agents