[all:vars]
# This sets the default user for all hosts in this file
ansible_user=edwin
force_k3s_reinstall=false
# Change this to 'wlan' for Wi-Fi connection, 'eth' for LAN cable connection
connection_mode=eth

[k3s_server]
# This host will use the default 'ansible_user=edwin'
# IP change detection: Update the IP when it changes. This will trigger a full cluster reinstall.
mantaray.local ansible_k3s_server_ip=192.168.1.141 ansible_host=192.168.1.141

[k3s_agents]
# These hosts override the default user
# Can simply disable the node by commenting out the line
rov.local     ansible_user=EEC ansible_k3s_agent_ip=192.168.1.219 ansible_host=192.168.1.219
rov-cam.local ansible_user=EEC ansible_k3s_agent_ip=192.168.1.14 ansible_host=192.168.1.14

[k3s_agents:vars]
ansible_python_interpreter=/usr/bin/python3

[all_nodes:children]
k3s_server
k3s_agents