# playbook.yaml

- name: Deploy Manta Ray ROS System to Kubernetes
  hosts: kube_masters
  gather_facts: false

  tasks:
    - name: Apply Kubernetes deployment manifests
      community.kubernetes.k8s:
        state: present
        src: "../kubernetes/manta-ray-deployment.yaml"