name: CI/CD Docker Build and Push to Docker Hub

on:
  push:
    branches: [ "feat/CICD_yuki" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # Setup Docker Buildx for better caching and speed up future builds
      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker buildx build --platform linux/amd64,linux/arm64 --file docker/common/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/manta-ray-ros:latest --push .